# Generated by Django 5.1.4 on 2024-12-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_rename_name_store_store_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='School',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='store_name',
            new_name='sch_name',
        ),
    ]
