# Generated by Django 5.1.4 on 2024-12-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_rename_store_school_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Location',
        ),
    ]
