# Generated by Django 5.1.4 on 2024-12-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_rename_school_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sch_name',
            field=models.CharField(max_length=10000),
        ),
    ]
