# Generated by Django 5.1.4 on 2024-12-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_location_sch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sch_name',
            field=models.TextField(),
        ),
    ]
